CREATE TABLE SED_Database.sedUI_session(
	session_id INT(10) ZEROFILL NOT NULL AUTO_INCREMENT PRIMARY KEY,
	scout_id INT(10) ZEROFILL NOT NULL,
	payment_method ENUM('Pay_Mail', 'Pay_Online') NOT NULL,
	payment_amount INT UNSIGNED,
	workshop1_id INT(10) ZEROFILL NOT NULL,
    workshop1_status ENUM('COMPLETE', 'INCOMPLETE', 'INPROGRESS') NOT NULL,
	workshop2_id INT(10) ZEROFILL,
    workshop2_status ENUM('COMPLETE', 'INCOMPLETE', 'INPROGRESS'),
	confirmation_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	event_checkin TIMESTAMP DEFAULT NULL,
	event_checkout TIMESTAMP DEFAULT NULL,
	workshop1_checkin TIMESTAMP DEFAULT NULL,
	workshop1_checkout TIMESTAMP DEFAULT NULL,
	workshop2_checkin TIMESTAMP DEFAULT NULL,
	workshop2_checkout TIMESTAMP DEFAULT NULL);