INSERT INTO sed_database.class 
	(class_id, class_name, class_description)
VALUES
	(1,"Astronomy",null),
    (2,"Aviation",null),
    (3,"Chemistry",null),
    (4,"Composite Materials",null),
    (5,"Drafting",null),
    (6,"Electricity",null),
    (7,"Electronics",null),
    (8,"Energy",null),
    (9,"Engineering",null),
    (10,"Game Design",null),
    (11,"model Design",null),
    (12,"Nuclear Science",null),
    (13,"Oceanography",null),
    (14,"Programming",null),
    (15,"Robotics",null),
    (16,"Space Exploration",null),
    (17,"Sustainability",null),
    (18,"Weather",null),
    (19,"Removed",null),
    (20,"Radio",null),
    (21,"Computers",null),
    (22,"Inventing",null);