# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sedUI', '0002_auto_20161026_0352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scout',
            name='phone',
        ),
        migrations.AddField(
            model_name='scout',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='scout',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
