# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sedUI', '0005_auto_20161026_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
